services:
  duaya_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: duaya-api:latest
    container_name: duaya_api
    restart: unless-stopped
    environment:
      LOG_LEVEL: "INFO"          # خليه DEBUG وقت التشخيص
      # SEARCH_TOP_K: "400"
      # SEARCH_MIN_SCORE10: "5.0"
      # EQ_TOP_K: "800"
      # EQ_MIN_BASE10: "0.0"
      PYTHONIOENCODING: "utf-8"
      TOKENIZERS_PARALLELISM: "false"
    ports:
      - "5543:5543"
    volumes:
      - ./chroma_db:/app/chroma_db:rw               # تخزين ChromaDB على الهوسـت
      - ./hf_cache:/root/.cache/huggingface:rw      # اختياري: كاش الموديلات
      - ./logs:/app/logs:rw                         # اختياري: لوجز
    command: >
      gunicorn -w 4 -k gthread --threads 8
      -b 0.0.0.0:5543
      app:app
      --access-logfile -
      --error-logfile -
      --timeout 120
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5543/health"]
      interval: 20s
      timeout: 5s
      retries: 5
