services:
  duaya_api:
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile
      # تقدر تشيل السطر ده لو مش هتستخدم stages، بس سيبه عادي
      target: dev
    image: duaya-api:dev
    container_name: duaya_api
    restart: unless-stopped

    environment:
      # نفس متغيّراتك + تمكين وضع التطوير
      LOG_LEVEL: "DEBUG"
      PYTHONIOENCODING: "utf-8"
      TOKENIZERS_PARALLELISM: "false"
      FLASK_ENV: development
      DEBUG: "true"
      HMAC_CLIENT_SECRETS: '{"duaya_index":"8ef5373b3b8b5aa0af7059f16bf8030657aa34e4bc5389f6290cfc0e6adef442","salamtk":"681ecfe6acf5bc26d5898046b51ddf8f45add546ae10ff5b33cbb950d66da64e"}'
      HMAC_TTL_SECONDS: "300"

    ports:
      - "5543:5543"

    # أهم نقطة: نعمل bind mount لفولدر المشروع كله جوّا /app
    # + باقي المجلدات الدائمة اللي عندك أصلاً
    volumes:
      - ./:/app:rw
      - ./chroma_db:/app/chroma_db:rw
      - ./hf_cache:/root/.cache/huggingface:rw
      - ./logs:/app/logs:rw

    # Gunicorn مع --reload عشان يلتقط أي تغييرات في الملفات
    # عاملين worker واحد بس في التطوير لتسريع إعادة التحميل
    command: >
      gunicorn -w 1 --reload --reload-engine=auto
      -k gthread --threads 8
      -b 0.0.0.0:5543
      app:app
      --access-logfile -
      --error-logfile -
      --timeout 120
      --log-level $${LOG_LEVEL:-DEBUG}

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5543/health"]
      interval: 20s
      timeout: 5s
      retries: 5
